### ISSUE TITLE
GAFs with fewer than 16 columns will have an array index error

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/gaferencer#11]
If Gaferencer is running on a gaf without an extends column or even just not enough columns, it can have an index out of bounds error. For example, the below line is from pseudocap. It only has 11 columns.

```
PseudoCAP    PA2574  alkB1           GO:0015976              ISS             P       alkane-1-monooxygenase          protein taxon:208964    20190311        PseudoCAP
```

The error from gaferencer looks like:
```
gaferencer gaf --ontfile true --contexts target/go_context.jsonld,target/obo_context.jsonld target/go-gaf.owl target/groups/pseudocap/pseudocap-src.gaf target/groups/pseudocap/pseudocap.gaferences.json
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 15
	at org.geneontology.gaferencer.Gaferencer$.processLine(Gaferencer.scala:110)
	at org.geneontology.gaferencer.Gaferencer$.$anonfun$parseGAF$2(Gaferencer.scala:83)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:480)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:486)
	at scala.collection.Iterator.toStream(Iterator.scala:1411)
	at scala.collection.Iterator.toStream$(Iterator.scala:1410)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1425)
	at scala.collection.TraversableOnce.toIterable(TraversableOnce.scala:295)
	at scala.collection.TraversableOnce.toIterable$(TraversableOnce.scala:295)
	at scala.collection.AbstractIterator.toIterable(Iterator.scala:1425)
	at org.geneontology.gaferencer.Gaferencer$.parseGAF(Gaferencer.scala:83)
	at org.geneontology.gaferencer.Gaferencer$.processGAF(Gaferencer.scala:27)
	at org.geneontology.gaferencer.Main$.delayedEndpoint$org$geneontology$gaferencer$Main$1(Main.scala:65)
	at org.geneontology.gaferencer.Main$delayedInit$body.apply(Main.scala:16)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.geneontology.gaferencer.Main$.main(Main.scala:16)
	at org.geneontology.gaferencer.Main.main(Main.scala)
```

**Comment by balhoff** [comment]
How is that example 11 columns? The taxon, date, and assigned by should be 13, 14, 15. Is it even parseable?

**Comment by balhoff** [comment]
@dougli1sqrd new release for you: https://github.com/geneontology/gaferencer/releases/tag/v0.4.1

**Comment by dougli1sqrd** [comment]
Ha it's not. pseudocap has a bunch of errors related to the gaf being bad.
